### ISSUE TITLE
workbench recipe: libglu dependency

### ISSUE THREAD

**Issue by yxqd** [mantidproject/conda-recipes#32]
should we use system glu like we did for framework, or use libglu from conda-forge?

See also: #31

**Comment by peterfpeterson** [comment]
maybe [freeglut](https://anaconda.org/conda-forge/freeglut) is the way to go

**Comment by peterfpeterson** [comment]
[here](https://github.com/AnacondaRecipes/libglu-feedstock/blob/master/recipe/meta.yaml#L18) is the libglu `meta.yml`

**Comment by marshallmcdonnell** [comment]
Re #43 for more info

**Comment by peterfpeterson** [comment]
#43 will fix this issue
