### ISSUE TITLE
Switch from Python 3.7 -> 3.8 in the framework recipe

### ISSUE THREAD

**Issue by marshallmcdonnell** [mantidproject/conda-recipes#51]
To update the "cutting-edge" Mantid Python version, want to bump the [version of python](https://github.com/mantidproject/conda-recipes/blob/master/framework/conda_build_config.yaml#L1-L3) from 3.7 -> 3.8.

Need to see if it builds.

Report to:
 - @peterfpeterson 
 - @rosswhitfield 
 - @KedoKudo 
 - @quantumsteve 
 - Donnie Earnest
 - @mabrahamdevops 

Notify:
 - @DanNixon

**Comment by martyngigg** [comment]
Close this issue as the new packages are based on Python 3.8
