### ISSUE TITLE
DOCS_SCREENSHOTS CMake Flag Needs to Be Enabled

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/conda-recipes#68]
The algorithm docs pages are currently missing their dialog screenshots, warning that this flag needs to be enabled on packaged builds. As mentioned in [here](https://github.com/mantidproject/mantid/pull/33922#issuecomment-1127703730), the recipes need updating to account for this.

**Comment by martyngigg** [comment]
Fixed by #69
